name: CI/CD with AA Panel

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Step 3: Install dependencies and build the project
      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      # Step 4: Deploy to the server1
      - name: Deploy to AA Panel server
        env:
          SSH_HOST: 122.248.250.57
          SSH_USER: Admin
          SSH_KEY: -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAsefg73oD2PNYdcHH+rIDtuSfu8yr9/Mgm+LCJjiXrCZQLOYMWIf3
4NigLDvC2D+yjmcLh1Q1VnKf+cSkTWt/0aoyRG9lrZDyKCA+inmJqyu44DNiJp9MbNC+Vg
q+0srw2r1/d+CmPlLKr+Q7FwLhYbDEkondNj7ucloP+434LQsbVmHHuM3wCdn898EV9CKe
vyegmmfGRndeKIwxPbTktjcjo06Qs2LNlLmu11CRLm9xpE435zvihNSwgLWFXEfmpiYSad
la5XiCx/UpT3TKJWlWDdUwqL9efHn7tYziI1N7uL5LEXnfXg2c2mzzi/EGQVKTBOfh4VE2
xILDNmin/AaF8MhFwwsvZaXN81dKnp3q2FS1BGfhEqbXKDOAMoXQDLH4P7o2XgRr0DbrAN
u678Fm0uDD/zrGQvEPhW/GGh3DyVj+lxvqibG4K9P+/S6my9fKE0ocBvoSTuXgoymrOL0v
3Y7zduc5R8DMGQT48rwHZOUvcHDr3sEwfOBE1BBGSvo++CDx3I/L54VtZXgKO3LOy0xlH1
1uORRULr+AbVnkamWCJ3xavF6vHYovuxJL2YHBk9cFaXvD6UV5dicvZCxYr5fa41b0HA2A
PJtGxG6NdwXMO/ybvXXad59RxX6MeUMZ6POWm1Uobo7hcgzhF2uurYqqKOxrcRAlDXKbiX
MAAAdQL7gm/C+4JvwAAAAHc3NoLXJzYQAAAgEAsefg73oD2PNYdcHH+rIDtuSfu8yr9/Mg
m+LCJjiXrCZQLOYMWIf34NigLDvC2D+yjmcLh1Q1VnKf+cSkTWt/0aoyRG9lrZDyKCA+in
mJqyu44DNiJp9MbNC+Vgq+0srw2r1/d+CmPlLKr+Q7FwLhYbDEkondNj7ucloP+434LQsb
VmHHuM3wCdn898EV9CKevyegmmfGRndeKIwxPbTktjcjo06Qs2LNlLmu11CRLm9xpE435z
vihNSwgLWFXEfmpiYSadla5XiCx/UpT3TKJWlWDdUwqL9efHn7tYziI1N7uL5LEXnfXg2c
2mzzi/EGQVKTBOfh4VE2xILDNmin/AaF8MhFwwsvZaXN81dKnp3q2FS1BGfhEqbXKDOAMo
XQDLH4P7o2XgRr0DbrANu678Fm0uDD/zrGQvEPhW/GGh3DyVj+lxvqibG4K9P+/S6my9fK
E0ocBvoSTuXgoymrOL0v3Y7zduc5R8DMGQT48rwHZOUvcHDr3sEwfOBE1BBGSvo++CDx3I
/L54VtZXgKO3LOy0xlH11uORRULr+AbVnkamWCJ3xavF6vHYovuxJL2YHBk9cFaXvD6UV5
dicvZCxYr5fa41b0HA2APJtGxG6NdwXMO/ybvXXad59RxX6MeUMZ6POWm1Uobo7hcgzhF2
uurYqqKOxrcRAlDXKbiXMAAAADAQABAAACAA9Cr7XQcUIL5bum1WD4zNQZxRCWnEMW9OYf
oRMm6ZkXvurgX5C8i75wIT/fbyBI89JpSRY2WqOWuN2eSOW8jJNPQSPuVk95eSbd/99gUO
HWTJ6Badrxm9xTBPCxLUXm/fAVhI346ZRmWlfqK54Ws39DatPocDRLWP2Fd4zW1GywtjXx
CfEdS94xzRRHg3rp+VS2W9LC3MGF/cAGqTangghAr0A+k1pVOwNAm5yBSbgs+8I3VMOeDG
6OfAbJC1krcGqHe4Q0OSrT7TalHgJgfJ08Quh0MB9Zgwu0aatcxrfMXSGEw+sKLuc3eGFN
f+Vc1ceGrhvOnulKo820KyCgq5VltR9/5cTPO1aYdMFwIhjxSGq/Ov7qNE4HNQmFe7flqF
PmxY2Ef0q6sy4qk3VqqxfbasvKU1z3xxGuBJrwQT5ExGX6EFwf0e8mrBmvsXTgMeXyN857
SVl0ghqNFfqrqfvvYFywW4Eoo/D685urIdd93bgo/3J+3wrF1TxKvT95IlVG/G9S9322Zv
KYePoI1djuVejsionelOj+1O3armhuqs8EeQibzUI05QxSr2BG4RS3E2hnv+p/yrTjDnN/
60GCg7UNimX70kQelHIOHx63VSxeHVQPjkfmC1xQAKIae616iJZGt9HULBjGYJIi2WiSzD
R6L5mg5alXpeyqL2WJAAABAFmchiizRwGRmGd+1BptO3pfzwwAGZRGVD8r/Z03p90ZU6rX
/d9jSMw0RUx/9nCG7XQllbC8EaMATxFcbOwPgrHaIW4rtbMe8w2EiG/9sNzzf2B0RQuhiX
a3LuLxr4TYCz5BDX7+QzsAwFwA6NSjBcfYI5MG+sTQ99ntUZyKc1z6MsNM1qWZZG2RnE3p
Wh4MbSu+8rmUe0Hf+8Jvmwwg0a0U9Ex/ReYF9bKAICV/goH8tBCZ8j+x+KmeCtw/oaFBMD
5IiXU3ZISTyFp3lXd8Q1y+5wxkVJtTU67AKM27sd6Ikj6+0o1ZRXCxc3YpZPsX43J0iFk/
4zj/v/cl/ry0OBsAAAEBAOmrtHNZQ4q9CpPQ3e33HCj0m09olcTJdkPpe/EltD4VmeaFWo
JLOFupdXoeuFoeDwnVK4I73nlmfxbxIpVQowEzkx/BA9gtImzAFkZvTecKuRNAfLUFIdb6
+gD5Hgz4BR+DvC8H+zF5UTqAk2+56lAYv930Z70pZ/jZEqA3xkf6KBFW0n1lmLoXH0c3hE
1kZA6KD+BwNi+3hwjXgn5c9V8oGh8ibMfwFtS0NAtR6tEYD+jP9nSfiRTW9pNOdDSjDRL3
kh/u0i9d/3aY2xCqNhRfNiiTiWgp/itqX4bdbm2BqmHROOryb0X0RkhjMVsekDUwpYAjLN
T1ZbPthV9TGyUAAAEBAMLn/nHMRTpnAmq91gcH1kZze2DfSTIWR5n/BSQa80fikoe+SxW6
ZVZHVO9U/SpSyzMo88bSenGeuTEwkrCdwgGPKTGezkI0PnRwTbndA0h0bv4EjgRYwUJxAj
QZ8RWBapgmFBM9dWtKXtt0bqyJ2pvAte+NsYr+ZKYgdcXBsZxwF70JUKOOa3z3yLWpQ+L2
B4hEGRKyNY4/0JUTgmRvDoZj1Q0ZkQt90VrWKwl7opVizSCJFTvEW1Z9/H9Y5l1oKdg//4
3GadpTw+8OFwAH+P8/AoZJtKZHmpJ/aLY3UHFtDPv/Ixg55ELoddIBk4349RJcPqtF8xkW
V75uMYCd+rcAAAAZdGhhbnRseW5ubmFpbmdAb2JzLmNvbS5tbQEC
-----END OPENSSH PRIVATE KEY-----

          DEPLOY_PATH: /www/wwwroot/cicd.origin.com.mm
        run: |
          echo "${SSH_KEY}" > deploy_key
          chmod 600 deploy_key
          rsync -avz -e "ssh -i deploy_key -o StrictHostKeyChecking=no" \
            ./build/ ${SSH_USER}@${SSH_HOST}:${DEPLOY_PATH}
          ssh -i deploy_key -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} <<EOF
          cd ${DEPLOY_PATH}
          # Restart your application (if applicable, e.g., PM2 or Node.js)
          pm2 restart all || pm2 start npm --name "admin-panel" -- start
#EOF
